#
# SPDX-License-Identifier: Apache-2.0
#
---
state: present
# api_endpoint:
# api_authtype:
# api_key:
# api_secret:
# api_token_endpoint:
# organization_name:
# ca_admin_enrollment_id
# ca_admin_enrollment_secret
# organization_admin_enrollment_id:
# organization_admin_enrollment_secret:
# peer_enrollment_id
# peer_enrollment_secret
ca_name: "{{ organization_name }} CA"
# ca_resources:
# ca_storage:
# ca_version:
peers: 1
peer_name: "{{ organization_name }} Peer"
# peer_resources:
# peer_storage:
peer_state_db: couchdb
# peer_version:
wallet: "{{ playbook_dir }}"
ca_admin_identity: "{{ wallet }}/{{ ca_name }} Admin.json"
organization_admin_identity: "{{ wallet }}/{{ organization_name }} Admin.json"
