#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Delete certificate authority
  ibm.blockchain_platform.certificate_authority:
    state: "{{ state }}"
    api_endpoint: "{{ api_endpoint }}"
    api_authtype: "{{ api_authtype }}"
    api_key: "{{ api_key }}"
    api_secret: "{{ api_secret | default(omit) }}"
    api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
    name: "{{ ca_name }}"

- name: Delete certificate authority admin
  ibm.blockchain_platform.enrolled_identity:
    state: "{{ state }}"
    api_endpoint: "{{ api_endpoint }}"
    api_authtype: "{{ api_authtype }}"
    api_key: "{{ api_key }}"
    api_secret: "{{ api_secret | default(omit) }}"
    api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
    path: "{{ playbook_dir }}/{{ ca_name }} Admin.json"

- name: Delete organization admin
  ibm.blockchain_platform.enrolled_identity:
    state: "{{ state }}"
    api_endpoint: "{{ api_endpoint }}"
    api_authtype: "{{ api_authtype }}"
    api_key: "{{ api_key }}"
    api_secret: "{{ api_secret | default(omit) }}"
    api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
    path: "{{ playbook_dir }}/{{ organization_name }} Admin.json"

- name: Delete organization
  ibm.blockchain_platform.organization:
    state: "{{ state }}"
    api_endpoint: "{{ api_endpoint }}"
    api_authtype: "{{ api_authtype }}"
    api_key: "{{ api_key }}"
    api_secret: "{{ api_secret | default(omit) }}"
    api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
    name: "{{ organization_name }}"

- name: Delete peer
  ibm.blockchain_platform.peer:
    state: "{{ state }}"
    api_endpoint: "{{ api_endpoint }}"
    api_authtype: "{{ api_authtype }}"
    api_key: "{{ api_key }}"
    api_secret: "{{ api_secret | default(omit) }}"
    api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
    name: "{{ peer_name }}"
  when: peers == 1

- name: Delete multiple peers
  ibm.blockchain_platform.peer:
    state: "{{ state }}"
    api_endpoint: "{{ api_endpoint }}"
    api_authtype: "{{ api_authtype }}"
    api_key: "{{ api_key }}"
    api_secret: "{{ api_secret | default(omit) }}"
    api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
    name: "{{ peer_name }}{{ item }}"
  loop: "{{ range(1, peers + 1, 1) | list }}"
  when: peers > 1
