#
# SPDX-License-Identifier: Apache-2.0
#
---
galaxy_info:
  author: Simon Stone
  description: Ansible role for deploying the IBM Blockchain Platform custom resource definitions into Kubernetes or Red Hat OpenShift
  license: Apache-2.0
  platforms:
    - name: GenericLinux
      versions:
        - all
  galaxy_tags: []
  min_ansible_version: "2.9"
